name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install Dioxus CLI
        uses: taiki-e/install-action@v1
        with:
          tool: dioxus-cli@0.4.1
      - uses: actions/checkout@v2
      - name: Build
        run: dx build --release --features web && cargo run --release --features prebuild && cp docs/index.html docs/404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: .
          clean: false # don't scrub docs